# Generated by Django 2.2.16 on 2023-01-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230113_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка', null=True, upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
